spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: mysecretpassword

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: true

jwt:
  secret: b1836507e0ad880977d9ba9c447d258f9b209196c7e8c9f4c41b0f2f4c938953